### ISSUE TITLE
Issues with RX v4

### ISSUE THREAD

**Issue by matthid** [fsprojects/FSharp.Control.Reactive#106]
### Description

See https://github.com/fsharp/FAKE/issues/1966
As I have understood it they have merged all their packages into one (`System.Reactive`) which breaks as existing packages still depend on the other assemblies.

### Suggested fix

Upgrade and release a new version :)

### Workaround for downstream

Add a dependency to `System.Reactive.Compatibility`, just like @kblohm suggests in https://github.com/fsharp/FAKE/pull/1967

**Comment by kblohm** [comment]
This should be fixed with 4.1.

**Comment by panesofglass** [comment]
Fixed in #107.
