### ISSUE TITLE
GIFs are not showing on the introduction page

### ISSUE THREAD

**Issue by stijnmoreels** [fsprojects/FSharp.Control.Reactive#114]
On the [introduction page](http://fsprojects.github.io/FSharp.Control.Reactive/introduction.html) the GIFs showing the result of the observables are not found:

![image](https://user-images.githubusercontent.com/9039753/43956341-132b1054-9ca4-11e8-9327-05be427cbc7e.png)

**Comment by panesofglass** [comment]
Probably an https vs http thing. I'll take a look.

**Comment by panesofglass** [comment]
Fixed.
