### ISSUE TITLE
can i reduce observe{} with rxquery{} ?

### ISSUE THREAD

**Issue by xp44mm** [fsprojects/FSharp.Control.Reactive#120]
Both `observe {...}` and `rxquery {...}` is `IObservalbe<'T>` type, so why don't merge them to one? any name but return type name is a good choice `observable`.

**Comment by panesofglass** [comment]
Good question. I don't have a specific example, but the two work slightly differently. You can, for instance, use an `if ... then ...` expression within `observe { ... }` but not within `rxquery { ... }` as the latter is a query expression and explicitly prohibits certain expressions. You can mix and match these expressions within each other, but they are better kept separate.
