### ISSUE TITLE
switchAsync and switchTask do not respect cancellation 

### ISSUE THREAD

**Issue by deviousasti** [fsprojects/FSharp.Control.Reactive#154]
This is similar to #137. 

The expected behavior of the `switch` operator is to dispose the subscription to the previously projected observable - this is part of what makes switch very useful.

We're not passing in the cancellation token, so `switchAsync` ends up running the async in the background even though the subscription is lost. We should probably fix this to make it so that `switchAsync` and `switchTask` behaves like map followed by a switch.

**Comment by deviousasti** [comment]
@panesofglass Shall I push a PR for this?

**Comment by panesofglass** [comment]
@deviousasti please do, if you have the time!

**Comment by panesofglass** [comment]
By the way, would you like to become a contributor? You have made several excellent contributions, and I'd love to remove any blockers to you getting more fixes into the library.

**Comment by deviousasti** [comment]
Thank you for the vote of confidence. I spoke to Mathias from FSSF, and was given commit access. 

I hope to keep improving this library, and responding to issues.
I look forward to working with you. :)
