### ISSUE TITLE
Make this library trimmable

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/FSharp.Control.Reactive#164]
### Description

I am using this library in blazor wasm application, but this library's bundle size is 357kb. Which is a lot for a web application.
I also created similar ticket for FSharp.Data.Adaptive, which they already made it hanppen. https://github.com/fsprojects/FSharp.Data.Adaptive/issues/104
And the result is pretty good.

### Known workarounds

People can add below stuff to their own application to make it work. But it is better to have it support by default.

```xml
<Target Name="ConfigureTrimming" BeforeTargets="PrepareForILLink">
<ItemGroup>
	<ManagedAssemblyToLink Condition="'%(Filename)' == 'FSharp.Control.Reactive'">
		<TrimMode>link</TrimMode>
		<IsTrimmable>true</IsTrimmable>
	</ManagedAssemblyToLink>
</ItemGroup>
</Target>
```

**Comment by deviousasti** [comment]
This is a good idea. Does `System.Reactive` support trimming as well?

**Comment by deviousasti** [comment]
I don't think we explicitly need to specify `TrimMode` since link is the default.
