### ISSUE TITLE
Is Observable.fromEventGeneric constrained too much?

### ISSUE THREAD

**Issue by shirok1** [fsprojects/FSharp.Control.Reactive#167]
https://github.com/fsprojects/FSharp.Control.Reactive/blob/ef1d7c629a8d522abe2101a2a9b1e63038f2f242/src/FSharp.Control.Reactive/Observable.fs#L744

Writing `Observable.fromEventGeneric event.AddHandler event.RemoveHandler` will prompt that `'a -> unit` is not implying delegate, however, `System.Reactive.Linq.Observable.FromEvent(event.AddHandler, event.RemoveHandler)` works just fine. I actually write my own helper function:

```fsharp
let toObservable (event: IEvent<'a, 'b>) : IObservable<'b> =
//    Observable.fromEventGeneric event.AddHandler event.RemoveHandler
    System.Reactive.Linq.Observable.FromEvent(event.AddHandler, event.RemoveHandler)
```

I wonder if this is by design.

**Comment by deviousasti** [comment]
The method you're referring to is specifically used to convert an delegate event of type [Action](https://docs.microsoft.com/en-us/dotnet/api/system.action-1?view=net-6.0). In C#, this would be declared as:
```
public event Action<TEventArgs> Event;
```

`IEvent` is native to F# already implements `IObservable`. 

```
type IEvent<'Delegate,'Args> =
  inherit System.IObservable<'Args> inherit IDelegateEvent<'Delegate>
```

so unlike a .NET event delegate, to convert from an F# event to observable, a static cast is sufficient. i.e,
```
let toObservable (event: IEvent<'a, 'b>) : IObservable<'b> =
    event :> IObservable<_>
```

**Comment by shirok1** [comment]
I see.
