### ISSUE TITLE
Incompatible with System.Reactive v6?

### ISSUE THREAD

**Issue by Micha-kun** [fsprojects/FSharp.Control.Reactive#169]
### Description

I tried to upgrade System.Reactive to latest version (v6), but VS2022 doesn't build because FSharp.Control.Reactive has a < v6 restriction

### Repro steps

Upgrade System.Reactive NuGet to v6.*

### Expected behavior

Solution compiles happy.

### Actual behavior

VS2022 cries in despair.

**`error NU1608: Warning As Error: Detected package version outside of dependency constraint: FSharp.Control.Reactive 5.0.5 requires System.Reactive (>= 5.0.0 && < 6.0.0) but version System.Reactive 6.0.0 was resolved.`**

### Known workarounds

I don't know workarounds

### Related information 

* Windows 10
* Visual Studio 2022
* .NET Core 3.1
* FSharp.Control.Reactive v5.0.5

**Comment by deviousasti** [comment]
Yes, I've been meaning to do this since the Rx 6 announcement.
Thank you for creating an issue.

**Comment by Micha-kun** [comment]
Is there any plan for this update? More and more reactive frameworks are swapping into Rx 6 :(

**Comment by glchapman** [comment]
Apologies for commenting on a closed issue, but I just checked Nuget, and its most recent version of FSharp.Control.Reactive is 5.0.5 (uploaded 5/3/2022). Any chance of getting the version with the relaxed restriction uploaded to Nuget?
