### ISSUE TITLE
What is the reason to support so many target frameworks?

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/FSharp.Control.Reactive#170]
I think this list is enough:

1.  `netstandard2.0`
2.  `net5.0`
3.  `net6.0`

**Comment by deviousasti** [comment]
Older framework apps (especially WPF apps) using Rx target `net472`, not `netstandard20` because the target sizes are much larger when you bring in a single `netstandard20` assembly. 
We'll have to support `net472` as a target as long as `System.Reactive` actively supports it.
