### ISSUE TITLE
Nuget won't load this package in Profile259

### ISSUE THREAD

**Issue by andybrackley** [fsprojects/FSharp.Control.Reactive#29]
Not sure whether I'm doing something wrong but when I try to import this package via Nuget into a project targeting Profile259 I get the error:

Install failed. Rolling back...
Could not install package 'FSharp.Control.Reactive 2.3.5'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+wp80+MonoAndroid10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Are there any plans to support this profile?

Thanks

**Comment by panesofglass** [comment]
This is coming soon; we just need a working build.

**Comment by panesofglass** [comment]
This _should_ get fixed in #83

**Comment by panesofglass** [comment]
Please check https://www.nuget.org/packages/FSharp.Control.Reactive
