### ISSUE TITLE
PCL 259 Support?

### ISSUE THREAD

**Issue by bordoley** [fsprojects/FSharp.Control.Reactive#54]
Can FSharp.Control.Reactive be released as a PCL (preferably profile 259) instead of net40? AFAICT from browsing the code there isn't anything that would require non PCL friendly code. RX is already distro'd with PCL 259 and this would enable use of the library on mobile platforms in addition to traditional desktop/server applications.

**Comment by panesofglass** [comment]
It's a matter of updating the build script. I've wanted to tackle multiple targets for awhile, but I've not had the time to make the attempt. Would you be interested in contributing that?

**Comment by bordoley** [comment]
Yeah if you can point me in the right direction. I'm not as familiar with all the tools used in the build, so it might take me a bit to ramp up.

**Comment by panesofglass** [comment]
I wish I could. I'm about to try this with a few other projects, so I might be able to leverage that learning back to this project soon. I think it may be as simple as creating a list of targets and MSBuild parameters, then running the build task with the appropriate parameters and generating NuGet packages from that.

**Comment by cloudRoutine** [comment]
Added in #74
