### ISSUE TITLE
Compiler warnings about RxQueryBuilder

### ISSUE THREAD

**Issue by bordoley** [fsprojects/FSharp.Control.Reactive#57]
The following RxQueryBuilder methods all result in compiler warnings about utilizing deprecated constructs. Frankly I would recommend removing these and replacing them with their IObservable duals. (SingleAsync, SingleOrDefaultAsync, FirstAsync, etc.) as the blocking methods are deadlock prone.

member __.ExactlyOne (s:IObservable<_>) = s.Single()
member __.ExactlyOneOrDefault (s:IObservable<_>) = s.SingleOrDefault()
member __.Find (s:IObservable<_>, [<ProjectionParameter>] predicate : _ -> bool) = s.First(new Func<_,bool>(predicate))
 member __.Head (s:IObservable<_>) = s.First()
member __.HeadOrDefault (s:IObservable<_>) = s.FirstOrDefault()
member __.Last (s:IObservable<_>) = s.Last()
member __.LastOrDefault (s:IObservable<_>) = s.LastOrDefault()

**Comment by panesofglass** [comment]
Fixed and will release as 3.1.0.
