### ISSUE TITLE
System.Reactive.Disposables wrappers

### ISSUE THREAD

**Issue by bordoley** [fsprojects/FSharp.Control.Reactive#58]
It would be really useful if this library provided some F# friend module functions that wrap the Disposables supported by RX. Specifically, I'm thinking something like

module Disposables =
    let composite (disposables:IEnumerable<IDisposable) =
        let retval = new CompositeDisposable()
        for disposable in do retval.Add disposable
        retval :> IDisposable

**Comment by panesofglass** [comment]
Please send a PR. This would be great!

**Comment by panesofglass** [comment]
I think your snippet above is:

``` fsharp
module Disposables =
    let composite (disposables:IEnumerable) =
        let retval = new CompositeDisposable()
        for disposable in disposables do
            retval.Add disposable
        retval :> IDisposable
```
