### ISSUE TITLE
Observable.combineLatest should return a tuple

### ISSUE THREAD

**Issue by bordoley** [fsprojects/FSharp.Control.Reactive#60]
In C# it requires the map function because tuples weren't part of .NET 4, and they're not that nice to work with in C#, but in F# the map function is painful. Let me know, I can submit a pr for this too once approved.

**Comment by panesofglass** [comment]
Please submit a PR. I'm not terribly familiar with this combinator nor why it should return a tuple. I'm interested to see your PR!

**Comment by bordoley** [comment]
I'm a little swamped this week trying to get a library I'm trying to finish into a releasable state, but I'll get you PRs for all these in a week or two.

**Comment by panesofglass** [comment]
Fantastic! Thank you!
