### ISSUE TITLE
Observable.SubscribeOn overload missing

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/FSharp.Control.Reactive#62]
I just noticed this this other day that this is missing an overload of Observable.SubscribeOn.  I would send a PR for it but there's an issue I found doing so.

There are the overloads for observeOn provided

    let observeOn (scheduler:Concurrency.IScheduler)
    let observeOnContext (context:SynchronizationContext)

There is a "subscribeOn" provided with the SynchronizationContext 

    let subscribeOn (context:Threading.SynchronizationContext) 

but no version provided with the IScheduler.

If I introduce something like subscribeOnScheduler 

     let subscribeOnScheduler (scheduler:Reactive.Concurrency.IScheduler)

This will now have an odd naming convention, but the other option is to break the existing API.

What do you think we should do?

**Comment by panesofglass** [comment]
I'd say break it. We could go for a major version number change or file it as a bug fix. Thoughts?

**Comment by TheAngryByrd** [comment]
I'm OK with breaking if it you are.  I'll send a PR soon.

**Comment by panesofglass** [comment]
This will be released as [3.2.0](www.nuget.org/packages/FSharp.Control.Reactive/3.2.0)
