### ISSUE TITLE
Consider removing isEmpty function

### ISSUE THREAD

**Issue by bordoley** [fsprojects/FSharp.Control.Reactive#68]
This method is dubious at best. The current implementation does a reference compare to the object returned by Observable.Empty() afaict.

```
  /// Determines whether the given observable is empty 
    let isEmpty source = source = Observable.Empty()
```

For instance this could easily result in a false result if an Observable was created from an empty array, or if the implementation of Observable.Empty() was changed not to return a singleton instance.

**Comment by panesofglass** [comment]
Rather than removing this, do you think we could fix it? Is it worth fixing?

**Comment by bordoley** [comment]
I don't think you can sanely fix the api. Consider an IObservable of mouse events or really any hot observable. What does it mean to be empty? Does empty really mean completed, and during the time I was observing it, no events were generated?

**Comment by panesofglass** [comment]
Good point

**Comment by cloudRoutine** [comment]
The implementation should have called `Observable.IsEmpty` from System.Reactive.Linq
The docstring for `isEmpty` should be more clear stating 
```
/// isEmpty returns an Observable that emits true if and only if the source 
/// Observable completes  without emitting any items. 
```

**Comment by bordoley** [comment]
@cloudRoutine good call on changing the method signature to return an observable. That makes sense. Thanks.
