### ISSUE TITLE
API reference documents have broken links

### ISSUE THREAD

**Issue by adicirstei** [fsprojects/FSharp.Control.Reactive#75]
The links pointing to source code in API reference documents are invalid.

The documents affected:
[Observable](http://fsprojects.github.io/FSharp.Control.Reactive/reference/fsharp-control-reactive-observablemodule.html)
[ObservableBuilder](http://fsprojects.github.io/FSharp.Control.Reactive/reference/fsharp-control-reactive-buildersmodule-observablebuilder.html)
[RxQueryBuilder](http://fsprojects.github.io/FSharp.Control.Reactive/reference/fsharp-control-reactive-buildersmodule-rxquerybuilder.html)

**Comment by panesofglass** [comment]
I think we just need to fix documentation generation. See #84.

**Comment by panesofglass** [comment]
I think these were all fixed in #110.
