### ISSUE TITLE
FSharp.Control.Reactive that's current on nuget.org (https://www.nuget.org/packages/FSharp.Control.Reactive/3.2.0) only has binaries in lib/net40

### ISSUE THREAD

**Issue by banshee** [fsprojects/FSharp.Control.Reactive#82]
I'd be nice to use this in other places than lib/net40 (Android/iOS)

**Comment by panesofglass** [comment]
I've started working on these tasks. I should have an updated build script by tomorrow night. I have most of it at least building, but I need to address a few more pieces.

**Comment by banshee** [comment]
Wonderful!  My plan was to get you pull requests for these, but other work got in the way.  I did report a paket bug (and it's fixed by the paket guys) that might be relevant; paket had a problem with + signs in directory names that got fixed, so make sure you're using paket >= 2.63.

**Comment by panesofglass** [comment]
See PR #83

**Comment by panesofglass** [comment]
New deployment available! https://www.nuget.org/packages/FSharp.Control.Reactive
