### ISSUE TITLE
3.4.0 drops support for net40?

### ISSUE THREAD

**Issue by deapsquatter** [fsprojects/FSharp.Control.Reactive#85]
### Description
3.4.0 no longer supports .NET 4.0
### Repro steps
Using Paket update 3.2.0 -> 3.4.0 and get warning:
```
Package FSharp.Control.Reactive contains libraries, but not for the selected TargetFramework net40 in project /Users/kevinknoop/Projects/agentNext/agent.mac/Agent.Mac.fsproj.
```
### Expected behavior
Paket should complete with no warnings.
### Actual behavior
Paket issues warning.
### Known workarounds
None
### Related information 
* Mac O SX
* Mono 4.4

**Comment by panesofglass** [comment]
Hmm ... I didn't even think to look at that bit, sorry. I take it you need support for net40. I'll see whether or not I can switch back to net40 from net45. No idea why the default was bumped up to net45.

**Comment by panesofglass** [comment]
@deapsquatter please try [3.4.1](https://www.nuget.org/packages/FSharp.Control.Reactive/3.4.1). This release now includes assemblies for net40, net45, and profile259.

**Comment by deapsquatter** [comment]
That fixes it. Thank you very much 👍
