### ISSUE TITLE
Tutorial doesn't compile

### ISSUE THREAD

**Issue by Lenne231** [fsprojects/FSharp.Control.Reactive#88]
### Description

The example on http://fsprojects.github.io/FSharp.Control.Reactive/tutorial.html doesn't seem to compile.
### Expected behavior

There should be no compiler error.
### Actual behavior

There is a compiler error:
"This value is not a function and cannot be applied"
### Known workarounds

`Observable.zip` expects two observables as parameters we have to use `Observable.zipWith` which expects a function as a first parameter and two observables.

https://github.com/fsprojects/fsharp.control.reactive/blob/5cee39af56fb732c2baa58bc3d1d791c34c21692/src/FSharp.Control.Reactive/Observable.fs#L1848

**Comment by panesofglass** [comment]
The fix is in the docs source but has not yet been published. 😖

**Comment by panesofglass** [comment]
Fixed in #110.
