### ISSUE TITLE
nuget package depends on rx-main 2.2.5, which has been pulled from nuget

### ISSUE THREAD

**Issue by sillyotter** [fsprojects/FSharp.Control.Reactive#89]
### Description

Rx-Main 2.2.5, the package this things current nuget package depends on, has been unlisted from nuget.  When they updated to v3.0 of rx.net, they changed the name to System.Reactive.  We might need a new release of this to track the new Rx library, assuming that they didn't break anything.

**Comment by panesofglass** [comment]
Ouch! I am surprised they pulled the package version. @cloudRoutine and I recently discussed the need to update this package to work with .NET Core, as well. We will try to get to that soon. If anyone else can get to it first, please do. I'm happy to review a PR!

**Comment by mikhail-aksenov** [comment]
Actually, I got a problem with moving a package to the Rx 3.0, because it seems like Rx team discarded support of 4.0 and 2.59 targets. Fortunately. it is still possible to build Control.Reactive for .NET 4.5 plus.

**Comment by TheAngryByrd** [comment]
Since https://github.com/fsprojects/FSharp.Control.Reactive/pull/90#partial-pull-merging was merge, can we get an alpha/beta nuget package? Pretty please? 🙏

**Comment by sillyotter** [comment]
Don't know if it will help anyone else, but while this has been going on, I have taken to using pakets github ability to just grab the Observable.fs file directly from the project and linking it directly into my project.

In the paket.dependencies:

    github fsprojects/FSharp.Control.Reactive src/FSharp.Control.Reactive/Observable.fs

and in paket.references:

    File: Observable.fs

And of course the needed `nuget System.Reactive.*` references as well.  Works quite well until a nuget package exists.

**Comment by dsyme** [comment]
@cloudRoutine @panesofglass Could you update the nuget package after recent merges please?

**Comment by cloudRoutine** [comment]
@panesofglass and @forki are the only ones who have access to the nuget packag

**Comment by forki** [comment]
@cloudRoutine what is your nuget name I can probably set that up for you.

**Comment by cloudRoutine** [comment]
it's also [cloudRoutine](https://www.nuget.org/profiles/cloudRoutine)

**Comment by forki** [comment]
> The user 'cloudRoutine' is already an owner or pending owner of this package.

so we tried that already ;-) 
Anyways I sent new invitation

**Comment by cloudRoutine** [comment]
I guess I missed the first invite, they should really list the pending invites on the profile page, but now I'm setup. I'll upload the new version today or tomorrow.

**Comment by mikhail-aksenov** [comment]
@cloudRoutine do you have any updates on NuGet?

**Comment by panesofglass** [comment]
Sorry for the long delay. I just published from AppVeyor. @cloudRoutine, send me your email, and I'll add you to the AppVeyor team so you, too, can deploy successfully built packages. I could also just auto-deploy, if you think that is better.
