### ISSUE TITLE
Subjects and Testing

### ISSUE THREAD

**Issue by stijnmoreels** [fsprojects/FSharp.Control.Reactive#96]
Hi all,

I wanted to expand the repository to include also `Subjects` and `Testing` operators. I created a separate branch: [testing-and-subjects](https://github.com/stijnmoreels/FSharp.Control.Reactive/tree/testing-and-subjects) where I tried to come up with some ideas.

Before I create a Pull Request; I want to make sure that my idea for expanding the API is OK and (if possible) we could make an extra NuGet package (ex. **FSharp.Control.Reactive.Testing**) where the testing-related functions are located.

Thanks in advance!

Greetings
Stijn

**Comment by panesofglass** [comment]
Yes, please do!
