### ISSUE TITLE
Dotnet Core support

### ISSUE THREAD

**Issue by palutz** [fsprojects/FSharp.Control.Reactive#97]
### Description
Add support to Donet core (ver >= 2.0)

Please provide a succinct description of your issue.
When adding this library to a dotnet core project (v. 2.0) you receive a warning of not fully compatible project.

### Repro steps
1. Create a new dotnet core project
    `dotnet new console -lang f#`
2. Add reference to FSharp.Control.Reactive
    `dotnet add package FSharp.Control.Reactive`
3. Try to build it
    `dotnet build/run`

### Actual behavior
Getting this warning
warning NU1701: Package 'Http.fs 4.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

* Operating system
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
* .NET Runtime, CoreCLR or Mono Version
Dotnet core 2.0.2
* Performance information, links to performance testing scripts

**Comment by panesofglass** [comment]
I think this is the same as #93, correct?

**Comment by palutz** [comment]
@panesofglass do you have any contrib guide that I can look at?
Can I try to build, or fix the build, also if I'm on Linux?

**Comment by panesofglass** [comment]
Yes, you should be able to do so. I don't think we have a contrib guide. You should be able to download the repo and build using `./build.sh All`.

**Comment by panesofglass** [comment]
As best I recall, the build runs successfully on Windows and macOS for me; I think the issue at this point is in the build configuration on the CI servers. However, it would be good to get additional feedback on what's going wrong, if anyone can reproduce the build failures. AppVeyor (Windows) appears to be failing b/c the CI is trying to run a target that no longer exists. I need @cloudRoutine to help resolve that one.

**Comment by palutz** [comment]
@panesofglass  yeap... all worked on my machine (Ubuntu 17.04). All green and no problem. Got only a warning about using xbuild, a deprecated tool, instead of msbuild.

**Comment by panesofglass** [comment]
Just released!
